spring.application.name=client-contacts-service
spring.datasource.url=jdbc:postgresql://localhost:5432/clients_contacts_db
spring.datasource.username=cc_admin
spring.datasource.password=cc_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog-master.yml
spring.liquibase.default-schema=public
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true